"""Tests for the QGRAF output parser."""
from pathlib import Path
import pytest

from feynman_engine.core.parser import parse_qgraf_output
from feynman_engine.core.models import Diagram

FIXTURES = Path(__file__).parent / "fixtures"


def load_fixture(name: str) -> str:
    return (FIXTURES / name).read_text()


class TestQEDTreeLevel:
    """Known-answer tests for QED tree-level processes."""

    def test_ee_to_mumu_single_diagram(self):
        """e+ e- → mu+ mu- at tree level must yield exactly 1 s-channel diagram."""
        raw = load_fixture("qed_tree_ee_mumu.txt")
        diagrams = parse_qgraf_output(raw, theory="QED", process="e+ e- -> mu+ mu-")

        assert len(diagrams) == 1

    def test_ee_to_mumu_structure(self):
        """Verify the s-channel diagram has correct structure."""
        raw = load_fixture("qed_tree_ee_mumu.txt")
        diagrams = parse_qgraf_output(raw, theory="QED", process="e+ e- -> mu+ mu-")
        d = diagrams[0]

        assert d.theory == "QED"
        assert d.process == "e+ e- -> mu+ mu-"
        assert len(d.vertices) == 2

    def test_ee_to_mumu_particles(self):
        """External particles should be e+, e-, mu+, mu-."""
        raw = load_fixture("qed_tree_ee_mumu.txt")
        d = parse_qgraf_output(raw, theory="QED", process="e+ e- -> mu+ mu-")[0]
        ext_particles = {e.particle for e in d.external_edges}

        assert "e-" in ext_particles
        assert "e+" in ext_particles
        assert "mu-" in ext_particles
        assert "mu+" in ext_particles

    def test_ee_to_mumu_internal_photon(self):
        """The internal propagator should be a photon."""
        raw = load_fixture("qed_tree_ee_mumu.txt")
        d = parse_qgraf_output(raw, theory="QED", process="e+ e- -> mu+ mu-")[0]
        internal_particles = [e.particle for e in d.internal_edges]

        assert "gamma" in internal_particles

    def test_ee_to_mumu_loop_order(self):
        """Tree-level diagram should have loop_order == 0."""
        raw = load_fixture("qed_tree_ee_mumu.txt")
        d = parse_qgraf_output(raw, theory="QED", process="e+ e- -> mu+ mu-")[0]
        assert d.loop_order == 0

    def test_bhabha_two_diagrams(self):
        """Bhabha scattering (e+ e- → e+ e-) at tree level: 2 diagrams (s and t)."""
        raw = load_fixture("qed_tree_bhabha.txt")
        diagrams = parse_qgraf_output(raw, theory="QED", process="e+ e- -> e+ e-")
        assert len(diagrams) == 2

    def test_sign_parsing(self):
        """Symmetry factor / sign is extracted correctly."""
        raw = load_fixture("qed_tree_ee_mumu.txt")
        d = parse_qgraf_output(raw, theory="QED", process="e+ e- -> mu+ mu-")[0]
        assert d.symmetry_factor == 1.0

    def test_bhabha_sign_negative(self):
        """Second Bhabha diagram has sign -1."""
        raw = load_fixture("qed_tree_bhabha.txt")
        diagrams = parse_qgraf_output(raw, theory="QED", process="e+ e- -> e+ e-")
        signs = {d.id: d.symmetry_factor for d in diagrams}
        assert signs[1] == 1.0
        assert signs[2] == -1.0


class TestParserEdgeCases:
    def test_empty_output_raises(self):
        """Empty QGRAF output should return empty list (no D…END blocks)."""
        diagrams = parse_qgraf_output("", theory="QED", process="test")
        assert diagrams == []

    def test_no_blocks_returns_empty(self):
        """Output with no D/END blocks (e.g. just QGRAF header) returns empty list."""
        header = "% file generated by qgraf-3.6.10\n% some comment\n"
        diagrams = parse_qgraf_output(header, theory="QED", process="test")
        assert diagrams == []

    def test_truncated_block_raises(self):
        """A D line without a closing END should not appear as a diagram."""
        truncated = "D 1 + 1\nI ep -1 p1\n"   # no END line
        diagrams = parse_qgraf_output(truncated, theory="QED", process="test")
        assert diagrams == []
